spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/ov_board_tasks
    username: root
    password: root
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true